language: rust
node_js:
  - "12"
rust:
  - stable
dist: xenial
services:
  - xvfb
before_install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh | sh
  - nvm install 12
  - npm run preinstall
install: npm ci
script: npm test