language: node_js
node_js:
  - "12"
rust:
  - stable
dist: xenial
services:
  - xvfb
before_install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - npm run preinstall
script: npm test